services:

  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:8080"
    depends_on:
      - identity
      - resource
      - booking
      - payment
      - community
      - ai

  identity:
    build:
      context: ./services/identity
    expose:
      - "8080"

  resource:
    build:
      context: ./services/resource
    expose:
      - "8080"

  booking:
    build:
      context: ./services/booking
    expose:
      - "8080"

  payment:
    build:
      context: ./services/payment
    expose:
      - "8080"

  community:
    build:
      context: ./services/community
    expose:
      - "8080"

  ai:
    build:
      context: ./ai
    expose:
      - "8000"